// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApi.Models.Ausleihe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Ausleihdatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ausweisnummer")
                        .HasColumnType("int");

                    b.Property<string>("Buchnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Rueckgabedatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ausweisnummer");

                    b.HasIndex("Buchnummer");

                    b.ToTable("Ausleihen");
                });

            modelBuilder.Entity("LibraryApi.Models.Buch", b =>
                {
                    b.Property<string>("Buchnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AutorInnen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Erscheinungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sachgebiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verlagsort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Buchnummer");

                    b.ToTable("Buecher");
                });

            modelBuilder.Entity("LibraryApi.Models.SchülerIn", b =>
                {
                    b.Property<int>("Ausweisnummer")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ausweisnummer");

                    b.ToTable("SchülerIn");
                });

            modelBuilder.Entity("LibraryApi.Models.Ausleihe", b =>
                {
                    b.HasOne("LibraryApi.Models.SchülerIn", "SchülerIn")
                        .WithMany("Ausleihen")
                        .HasForeignKey("Ausweisnummer");

                    b.HasOne("LibraryApi.Models.Buch", "Buch")
                        .WithMany("Ausleihen")
                        .HasForeignKey("Buchnummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buch");

                    b.Navigation("SchülerIn");
                });

            modelBuilder.Entity("LibraryApi.Models.Buch", b =>
                {
                    b.Navigation("Ausleihen");
                });

            modelBuilder.Entity("LibraryApi.Models.SchülerIn", b =>
                {
                    b.Navigation("Ausleihen");
                });
#pragma warning restore 612, 618
        }
    }
}
